### ISSUE TITLE
Deploy on private network

### ISSUE THREAD

**Issue by alexkubica** [apache/incubator-openwhisk-deploy-openshift#2]
I just posted [this stackoverflow question](https://stackoverflow.com/questions/51513857/pull-all-images-defined-in-an-openshift-template-file) about how can I easily pull all images from your template file and was hoping you could help me.
tl;dr I want to deploy openwhisk on my own openshift server hosted on a private netwrok where I don't have access to docker's official repository.

How can I do this?

**Comment by bbrowning** [comment]
I don't know of an easy way to pull all images from the template, although perhaps some shell scripting and template parsing could accomplish that, combined with the example of how to pull a single image from the reply to that stackoverflow question?
