### ISSUE TITLE
Does not deploy on OpenShift Container Platform 3.10

### ISSUE THREAD

**Issue by wkulhanek** [apache/incubator-openwhisk-deploy-openshift#4]
It fails on creating the Cronjobs because the API version changed.

Needs 'batch/v1beta1' instead of 'batch/v2alpha1' for the apiVersion of the two Cronjobs.

**Comment by bbrowning** [comment]
Thanks for the bug report! We don't test against OpenShift Container Platform here, but we can add its upstream, OKD 3.10, to the CI matrix and get this fixed.

**Comment by varesa** [comment]
+1, also affects OKD 3.11 which is the current/latest release

**Comment by dgrove-oss** [comment]
Closing issue to prepare to archive project.  Deploying on OpenShift now supported by https://github.com/apache/openwhisk-deploy-kube.
