### ISSUE TITLE
use of wskadmin

### ISSUE THREAD

**Issue by h4wkmoon** [apache/incubator-openwhisk-deploy-openshift#8]
Hi, 
The deployment of openwhisk in our openshift 3.9 went well.
But now, we need to add users, namespaces, ... 
I read with wskadmin is the tool for that.
How can I configure it, plz ?

> property "DB_WHISK_AUTHS" not found in environment or property file
> property "WHISK_LOGS_DIR" not found in environment or property file
> property "DB_PASSWORD" not found in environment or property file
> property "DB_PORT" not found in environment or property file
> property "DB_PROTOCOL" not found in environment or property file
> property "DB_WHISK_ACTIONS" not found in environment or property file
> property "DB_HOST" not found in environment or property file
> property "DB_WHISK_ACTIVATIONS" not found in environment or property file
> property "DB_USERNAME" not found in environment or property file

**Comment by h4wkmoon** [comment]
it looks like wskmadin pod is missing in openshift deployment. (present in incubator-openwhisk-deploy-kube)

**Comment by mrutkows** [comment]
@h4wkmoon Members of the RH team provided this deployment code drop primarily for experimental use by the community to better understand how OpenShift uses OW as we make changes to the Control and Data planes moving forward.  @bbrowning @bwmcadams do you have any official comments in this regard?

**Comment by h4wkmoon** [comment]
I manage to make a wskadmin pod (from the kube ow repo) work in openshift.
It is very quick and dirty. But it proves that it can be done.
Fyi, as projectodd does not provide a wskadmin image, I used the one from the ow kube repo.

When my work is less dirty, i should be able to publish it.

**Comment by rabbah** [comment]
Awesome! thanks @h4wkmoon.

**Comment by dgrove-oss** [comment]
Closing issue to prepare to archive project.  Deploying on OpenShift now supported by https://github.com/apache/openwhisk-deploy-kube.
